apiVersion: v1
kind: Pod
metadata:
  name: pod-using-pvc
spec:
  containers:
  - image: alpine
    name: r-n-g
    command: ["/bin/sh", "-c", "shuf -i 0-100 -n 1 >> /opt/number.out; sleep 100"]
    volumeMounts:
    - name: from-pvc
      mountPath: "/opt"
  volumes:
  - name: from-pvc
    persistentVolumeClaim:
      claimName: myclaim
